spring:
  task:
    scheduling:
      pool:
        size: 10
  profiles:
    default: dev
server.port: ${PORT:8084}
logger:
  tg:
    chat: ${LOGGER_CHAT}
    level: INFO
    token: ${LOGGER_TOKEN}

bot:
  feedback:
    username: ${BOT_FEEDBACK_USERNAME:None}
    token: ${BOT_FEEDBACK_TOKEN:None}
  pidor:
    username: ${BOT_USERNAME}
    token: ${BOT_TOKEN}
telegraph:
  token: ${TELEGRAPH_TOKEN}
app:
  version: 11.1 Hot Potato
  admin.userId: ${ADMIN_USER_ID}
  time.bot.reconnect: 10000
  threadNum:
    sendMessages: 15
    tasks: 5

task:
  gameStart.cron: 0 1 21 * * ?
  hotPotatoAutoStrike.cron: 0 1 9 * * ?
  gameReminderTask.cron: 0 0 13 * * ?
  gameEnd.cron: 0 0 16 * * ?
  notifyNoPidors.cron: 0 0 17 * * ?
  notifyPidorOfTheMonthTask.cron: 0 0 18 * * ?
  pidorOfYear.cron: 0 0 19 31 12 ?
  futureAction.cron: 0 30 20 * * ?
  updateUsername.cron: 0 0 1 * * ?
  backup.cron: 0 0 20 * * ?
  hotPotatoCheckTask.delay: 55000