management:
  endpoint.health.show-details: always
  health:
    diskSpace.enabled: false
    refresh.enabled: false
    ping.enabled: false
spring:
  cloud.discovery.client.composite-indicator.enabled: false
  task:
    scheduling:
      pool:
        size: 10
  profiles:
    default: dev
server.port: ${PORT:8084}
logger:
  tg:
    enabled: true
    chat: ${LOGGER_CHAT:None}
    level: INFO
    token: ${LOGGER_TOKEN:None}
bot:
  feedback:
    username: ${BOT_FEEDBACK_USERNAME:None}
    token: ${BOT_FEEDBACK_TOKEN:None}
  pidor:
    username: ${BOT_USERNAME:None}
    token: ${BOT_TOKEN}
telegraph:
  token: ${TELEGRAPH_TOKEN:None}
app:
  admin.userId: ${ADMIN_USER_ID}
  time.bot.reconnect: 10000
  threadNum:
    sendMessages: 20
    tasks: 20
api:
  github:
    user: ${GITHUB_USER:None}
    repo: ${GITHUB_REPO:pidor-bot}
    branch: ${GITHUB_BRANCH:main}
    token: ${GITHUB_TOKEN:None}
task:
  gameStart.cron: 0 1 21 * * ?
  hotPotatoAutoStrike.cron: 0 1 9 * * ?
  gameReminderTask.cron: 0 0 13 * * ?
  gameEnd.cron: 0 0 16 * * ?
  notifyNoPidors.cron: 0 0 17 * * ?
  blackBoxStartTask.cron: 0 30 17 * * ?
  notifyPidorOfTheMonthTask.cron: 0 0 18 * * ?
  pidorOfYear.cron: 0 0 19 31 12 ?
  futureAction.cron: 0 30 20 * * ?
  updateUsername.cron: 0 0 1 * * ?
  backup.cron: 0 0 20 * * ?
  hotPotatoCheckTask.delay: 45000